"""Shared scaffolding for the retro-rewrite tool suite (p4-26).

The three retro-rewrite tools (`rename_tags.py`, `rename_canonical.py`,
`merge_categories.py`) are WRITE-class, use=retro-rewrite. They mutate
HISTORICAL classifications, but they NEVER edit historical ledger rows in
place — that is the append-only RED flag (shape.md Constraints; structured-
problem.md). The sanctioned mechanism (S5 p2-10, S4 p3-2, B2-IMP precedents):

  1. Append a row to the matching append-only corrections side-ledger
     (`tag-renames.csv` / `vendor-canonicals.csv` / `category-migrations.csv`).
     Rows are NEVER edited or deleted in place.
  2. Where a config file is the classifier's live source of truth (tags.json,
     suppliers.json, categories.json), update the config so future closes
     classify correctly. Config is regenerable agent-readable state, not a
     historical ledger.
  3. The derived output `transactions.csv` is regenerated by `categorize.py`,
     which joins the corrections + reads the updated config at read time.

These tools do NOT touch raw/historical ledger rows. They write only to the
corrections side-ledgers and the config files above.

This module provides the four non-negotiables shared by all three tools:

  * `--dry-run` is the DEFAULT. A real write requires an explicit `--apply`.
  * A fix-impact preview that enumerates EVERY affected location BEFORE any
    write (rows + configs + dashboard joins + tag namespaces + cross-tree deps).
  * A rollback path: every file a real run writes is first copied to a
    timestamped `.bak` beside it; `rollback()` restores from those backups.
  * An audit event per affected destination per run (via lib.audit, fail-soft).

Each tool builds an `ImpactReport` (a list of `Impact` rows), prints it, and —
only under `--apply` — performs its writes through `apply_writes()` which
handles backup-before-write and per-destination audit emission.
"""
from __future__ import annotations

import csv
import datetime as _dt
import json
import os
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

# Make sb-os/finance/scripts/shared/ importable for the audit helper, mirroring
# the existing migration idiom (2026-05-01-migrate-rf-juros.py).
_SHARED = Path(__file__).resolve().parents[1] / "shared"
if str(_SHARED) not in sys.path:
    sys.path.insert(0, str(_SHARED))
try:
    from lib import audit  # type: ignore  # noqa: E402
except Exception:  # pragma: no cover - audit is best-effort
    audit = None  # type: ignore


# ---------------------------------------------------------------------------
# Path resolution (env-overridable for test isolation; never hardcoded)
# ---------------------------------------------------------------------------


def find_vault_root() -> Path:
    """Walk up to the vault root (sb-os.json or .obsidian marker)."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "sb-os.json").exists() or (parent / ".obsidian").exists():
            return parent
    raise RuntimeError("Vault root not found (looking for sb-os.json or .obsidian)")


def bookkeeper_root() -> Path:
    """`.user/finance/bookkeeper/`, overridable via BOOKKEEPER_ROOT."""
    override = os.environ.get("BOOKKEEPER_ROOT")
    if override:
        return Path(override)
    return find_vault_root() / ".user" / "finance" / "bookkeeper"


def config_dir() -> Path:
    """Config dir, overridable via BOOKKEEPER_CONFIG_DIR (matches query tools)."""
    override = os.environ.get("BOOKKEEPER_CONFIG_DIR")
    if override:
        return Path(override)
    return bookkeeper_root() / "config"


def corrections_dir() -> Path:
    return config_dir() / "corrections"


def ledger_fechamento_dir() -> Path:
    override = os.environ.get("BOOKKEEPER_LEDGER_DIR")
    base = Path(override) if override else (bookkeeper_root() / "ledgers")
    return base / "fechamento"


def recurring_payments_path() -> Path:
    """Cross-tree dep: `2-areas/finance/pagamentos-recorrentes.md` (p2-7 §1.18).

    Overridable via BOOKKEEPER_RECURRING_PATH for test isolation.
    """
    override = os.environ.get("BOOKKEEPER_RECURRING_PATH")
    if override:
        return Path(override)
    return find_vault_root() / "2-areas" / "finance" / "pagamentos-recorrentes.md"


# ---------------------------------------------------------------------------
# Impact model
# ---------------------------------------------------------------------------


@dataclass
class Impact:
    """One affected location in the fix-impact preview.

    `kind` groups the surface (config / correction-ledger / output-rows /
    dashboard-join / tag-namespace / cross-tree-dep). `writable` is True when
    THIS tool will write the location under --apply; False when the location is
    only *affected downstream* (e.g. transactions.csv is regenerated by
    categorize.py, not by this tool) or is a manual/cross-tree dependency the
    user must reconcile by hand.
    """

    kind: str
    location: str
    detail: str
    writable: bool = False
    # For writable file locations: a callable that performs the write. Receives
    # no args; returns None. Only invoked under --apply, after backup.
    writer: Callable[[], None] | None = None
    # Materiality for the audit event emitted when this location is written.
    materiality: str = "high"


@dataclass
class ImpactReport:
    tool: str
    operation: str  # human-readable, e.g. "rename tag 'boxe' -> 'esportes-luta'"
    impacts: list[Impact] = field(default_factory=list)
    # Blocking problems found during impact analysis (e.g. target tag missing).
    # A non-empty list means the operation is refused even under --apply.
    errors: list[str] = field(default_factory=list)
    # Non-blocking advisories surfaced to the user (e.g. a dormant consumer).
    warnings: list[str] = field(default_factory=list)

    def add(self, *a, **kw) -> None:
        self.impacts.append(Impact(*a, **kw))

    def writable_impacts(self) -> list[Impact]:
        return [i for i in self.impacts if i.writable and i.writer is not None]


# ---------------------------------------------------------------------------
# Preview rendering
# ---------------------------------------------------------------------------


_KIND_ORDER = [
    "correction-ledger",
    "config",
    "output-rows",
    "dashboard-join",
    "tag-namespace",
    "cross-tree-dep",
]


def print_impact_report(report: ImpactReport, *, applying: bool) -> None:
    mode = "APPLY (writing)" if applying else "DRY-RUN (no writes)"
    print("=" * 78)
    print(f"  {report.tool} — fix-impact preview  [{mode}]")
    print(f"  Operation: {report.operation}")
    print("=" * 78)

    if report.errors:
        print("\nBLOCKING ERRORS — operation refused:")
        for e in report.errors:
            print(f"  ✗ {e}")

    if report.warnings:
        print("\nWARNINGS:")
        for w in report.warnings:
            print(f"  ! {w}")

    by_kind: dict[str, list[Impact]] = {}
    for imp in report.impacts:
        by_kind.setdefault(imp.kind, []).append(imp)

    ordered_kinds = [k for k in _KIND_ORDER if k in by_kind]
    ordered_kinds += [k for k in by_kind if k not in _KIND_ORDER]

    print(f"\nAffected locations ({len(report.impacts)} total):")
    for kind in ordered_kinds:
        print(f"\n  [{kind}]")
        for imp in by_kind[kind]:
            marker = "WRITE " if imp.writable else "affected"
            print(f"    - ({marker}) {imp.location}")
            if imp.detail:
                print(f"          {imp.detail}")

    n_writable = sum(1 for i in report.impacts if i.writable)
    print("\n" + "-" * 78)
    print(
        f"  {n_writable} location(s) this tool will WRITE under --apply; "
        f"{len(report.impacts) - n_writable} affected downstream / "
        f"manually."
    )
    if not applying:
        print("  DRY-RUN: nothing was written. Re-run with --apply to execute.")
    print("-" * 78)


# ---------------------------------------------------------------------------
# Backup / rollback
# ---------------------------------------------------------------------------


def _backup_token() -> str:
    return _dt.datetime.now().strftime("%Y%m%dT%H%M%S")


def backup_path_for(target: Path, token: str) -> Path:
    """Backup sits beside the target: `<name>.bak.<token>`."""
    return target.with_name(f"{target.name}.bak.{token}")


def apply_writes(
    report: ImpactReport,
    *,
    source_function: str,
) -> dict:
    """Execute every writable impact under a single backup token.

    For each writable location:
      1. If the destination file already exists, copy it to a timestamped
         `.bak.<token>` first (the rollback anchor). New files get no backup
         row but are recorded so rollback can delete them.
      2. Run the writer.
      3. Emit one audit event (best-effort, never raises).

    Returns a manifest dict (used by rollback + tests):
      {token, backups: [{target, backup, existed_before}], ...}
    """
    token = _backup_token()
    backups: list[dict] = []

    for imp in report.writable_impacts():
        target = Path(imp.location)
        existed_before = target.exists()
        backup = None
        if existed_before:
            backup = backup_path_for(target, token)
            shutil.copy2(target, backup)
        backups.append(
            {
                "target": str(target),
                "backup": str(backup) if backup else None,
                "existed_before": existed_before,
            }
        )

        # Perform the write.
        assert imp.writer is not None
        imp.writer()

        # One audit event per affected destination per run (fail-soft).
        if audit is not None:
            try:
                audit.emit(
                    "config_write",
                    source_function=source_function,
                    destination=target,
                    action="append" if imp.kind == "correction-ledger" else "overwrite",
                    materiality=imp.materiality,
                    summary={
                        "retro_rewrite": report.tool,
                        "operation": report.operation,
                        "kind": imp.kind,
                    },
                )
            except Exception:  # pragma: no cover - audit is best-effort
                pass

    manifest = {
        "tool": report.tool,
        "operation": report.operation,
        "token": token,
        "backups": backups,
    }
    return manifest


def rollback(manifest: dict) -> list[str]:
    """Restore prior state from an apply_writes() manifest.

    For each recorded target: restore its `.bak.<token>` (byte-for-byte) if one
    was made; if the target did NOT exist before the run (no backup), delete the
    file the run created. Returns a list of human-readable actions taken.
    """
    actions: list[str] = []
    # Reverse order so newer writes are undone first (defensive; order-agnostic
    # for independent files but correct if any future target nests).
    for entry in reversed(manifest.get("backups", [])):
        target = Path(entry["target"])
        backup = entry.get("backup")
        if entry.get("existed_before") and backup:
            shutil.copy2(backup, target)
            actions.append(f"restored {target.name} from {Path(backup).name}")
        elif not entry.get("existed_before"):
            if target.exists():
                target.unlink()
                actions.append(f"deleted {target.name} (did not exist before run)")
    return actions


def write_manifest(manifest: dict, *, label: str) -> Path:
    """Persist the apply manifest beside the corrections dir under
    `corrections/.rollback/<label>-<token>.json` so a later invocation (or the
    user) can roll the change back. Returns the manifest path.
    """
    rb_dir = corrections_dir() / ".rollback"
    rb_dir.mkdir(parents=True, exist_ok=True)
    path = rb_dir / f"{label}-{manifest['token']}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    return path


# ---------------------------------------------------------------------------
# Small IO helpers (UTF-8 everywhere — config files contain accented pt-BR)
# ---------------------------------------------------------------------------


def load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def dump_json(path: Path, data: dict) -> None:
    """Write JSON preserving the project's 2-space indent + non-ASCII chars."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")


def append_correction_row(path: Path, fieldnames: list[str], row: dict) -> None:
    """Append one row to an append-only corrections CSV, writing the header if
    the file is new/empty. NEVER rewrites existing rows."""
    exists = path.exists() and path.stat().st_size > 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not exists:
            writer.writeheader()
        writer.writerow(row)


def iter_transactions_rows():
    """Yield (month, csv_path, row_dict) across every fechamento transactions.csv.

    Read-only. Used to ENUMERATE affected output rows for the fix-impact
    preview — never to mutate them (categorize.py regenerates them).
    """
    base = ledger_fechamento_dir()
    if not base.exists():
        return
    for month_dir in sorted(base.iterdir()):
        if not month_dir.is_dir():
            continue
        txfile = month_dir / "transactions.csv"
        if not txfile.exists():
            continue
        with open(txfile, "r", encoding="utf-8", newline="") as f:
            for row in csv.DictReader(f):
                yield month_dir.name, txfile, row


def now_iso() -> str:
    return _dt.datetime.now().replace(microsecond=0).isoformat()
