"""merge_categories: retro-rewrite tool — merge one category into another (p4-26).

WRITE-class, use=retro-rewrite. The HIGHEST-blast-radius retro-rewrite: merges
category FROM into category TO (`--from old_cat --to keep_cat`) by:
  1. Appending a row to the append-only `corrections/category-migrations.csv`
     side-ledger (from_category -> to_category; the durable record; rows are
     never edited in place).
  2. Updating `config/categories.json` — every place a category value lives:
       * `categories`            (drop the FROM key — it ceases to be valid)
       * `value_based_mappings[].category`        (FROM -> TO)
       * `reimbursement_mappings.*.category` and bare-string values (FROM -> TO)
       * `recurrence_rules.default_by_category`   (FROM key -> TO key)
  3. Updating `config/suppliers.json` — `default_category` FROM -> TO on every
     supplier that defaulted to FROM (the classifier's live category source).

It NEVER edits historical ledger rows. The `category` column in
`transactions.csv` is regenerated by `categorize.py` from the updated config at
read time — this tool enumerates the affected rows but does not rewrite them.

Affected locations enumerated by the fix-impact preview, BEFORE any write:
  * correction-ledger: category-migrations.csv (append target)
  * config: categories.json (4 sub-surfaces above), suppliers.json default_category
  * output-rows: transactions.csv rows with category == FROM
  * dashboard-join: dashboard/expenses.js (reads categories.json live for
    category tables + reimbursement netting + color maps keyed on category)
  * cross-tree-dep: 2-areas/finance/pagamentos-recorrentes.md (a vault-content
    schedule with a Categoria column — MANUAL reconcile)

DRY-RUN IS THE DEFAULT. A real write requires --apply, is backed up before
writing, and is reversible via --rollback TOKEN.

Composes the existing read tool `query_corrections.py` to surface any prior
category-migration for FROM before writing a new one.

Usage:
    python merge_categories.py --from old --to keep             # DRY-RUN
    python merge_categories.py --from old --to keep --apply      # execute
    python merge_categories.py --rollback TOKEN                  # undo

Exit codes:
    0  preview rendered / apply succeeded / rollback succeeded
    1  blocking error (category missing, FROM==TO, etc.)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import _retro_rewrite_common as common  # noqa: E402

_TOOL = "merge_categories"
_CAT_MIGRATIONS_FIELDS = [
    "from_category",
    "to_category",
    "scope",
    "effective_after",
    "added_at",
    "source",
    "note",
]
# Dashboard file that reads categories.json live (enumerated as a join, never written).
_DASHBOARD_EXPENSES_JS = "dashboard/expenses.js"


def build_impact(
    from_cat: str,
    to_cat: str,
    *,
    source: str,
    note: str,
) -> common.ImpactReport:
    report = common.ImpactReport(
        tool=_TOOL, operation=f"merge category {from_cat!r} -> {to_cat!r}"
    )
    cfg = common.config_dir()
    categories_path = cfg / "categories.json"
    suppliers_path = cfg / "suppliers.json"
    cat_mig_path = common.corrections_dir() / "category-migrations.csv"

    if from_cat == to_cat:
        report.errors.append("--from and --to are the same category — nothing to merge.")
        return report

    if not categories_path.exists():
        report.errors.append(f"categories.json not found at {categories_path}")
        return report

    cat_doc = common.load_json(categories_path)
    categories = cat_doc.get("categories", {})

    if from_cat not in categories:
        report.errors.append(
            f"source category {from_cat!r} not found in categories.json "
            f"(present: {', '.join(sorted(categories))})"
        )
    if to_cat not in categories:
        report.errors.append(
            f"target category {to_cat!r} not found in categories.json — refusing to "
            f"merge into a non-existent category (would create an invalid category)."
        )

    # --- correction-ledger: category-migrations.csv (write target) ------------
    report.add(
        "correction-ledger",
        str(cat_mig_path),
        f"append row: from_category={from_cat}, to_category={to_cat}, scope=all",
        writable=True,
        materiality="high",
    )

    # --- config: categories.json (4 sub-surfaces) -----------------------------
    sub_surfaces = []
    if from_cat in categories:
        sub_surfaces.append("categories key (dropped)")
    vbm_hits = sum(
        1
        for m in (cat_doc.get("value_based_mappings") or [])
        if isinstance(m, dict) and m.get("category") == from_cat
    )
    if vbm_hits:
        sub_surfaces.append(f"value_based_mappings.category ×{vbm_hits}")
    reimb_hits = 0
    for _k, v in (cat_doc.get("reimbursement_mappings") or {}).items():
        if isinstance(v, dict) and v.get("category") == from_cat:
            reimb_hits += 1
        elif isinstance(v, str) and v == from_cat:
            reimb_hits += 1
    if reimb_hits:
        sub_surfaces.append(f"reimbursement_mappings.category ×{reimb_hits}")
    rr = cat_doc.get("recurrence_rules", {})
    dbc_hit = from_cat in (rr.get("default_by_category") or {})
    if dbc_hit:
        sub_surfaces.append("recurrence_rules.default_by_category key")

    report.add(
        "config",
        str(categories_path),
        f"rewrite {from_cat!r} -> {to_cat!r} in: {', '.join(sub_surfaces) or '(category key only)'}",
        writable=True,
        materiality="high",
    )

    # --- config: suppliers.json default_category (write target) ---------------
    sup_hits = []
    if suppliers_path.exists():
        sup_doc = common.load_json(suppliers_path)
        suppliers = sup_doc.get("suppliers", sup_doc)
        for slug, rec in suppliers.items():
            if isinstance(rec, dict) and rec.get("default_category") == from_cat:
                sup_hits.append(slug)
    if sup_hits:
        report.add(
            "config",
            str(suppliers_path),
            f"{len(sup_hits)} supplier(s) default to {from_cat!r} "
            f"({', '.join(sup_hits[:8])}{'…' if len(sup_hits) > 8 else ''}) — "
            f"rewrite default_category -> {to_cat!r}",
            writable=True,
            materiality="high",
        )

    # --- output-rows: transactions.csv category column (affected) -------------
    row_hits = 0
    months: set[str] = set()
    for month, _txfile, row in common.iter_transactions_rows():
        if (row.get("category", "") or "") == from_cat:
            row_hits += 1
            months.add(month)
    if row_hits:
        report.add(
            "output-rows",
            str(common.ledger_fechamento_dir()),
            f"{row_hits} transactions.csv row(s) across {len(months)} month(s) "
            f"({', '.join(sorted(months))}) carry category=={from_cat!r}. These "
            f"regenerate via categorize.py on the next close — NOT rewritten here.",
            writable=False,
        )

    # --- dashboard-join: expenses.js reads categories.json live ---------------
    report.add(
        "dashboard-join",
        _DASHBOARD_EXPENSES_JS,
        f"reads categories.json live for category tables + reimbursement netting "
        f"+ the category color map. After the merge, {from_cat!r} disappears from "
        f"the dashboard automatically (no JS edit needed); verify the color map "
        f"has no hardcoded {from_cat!r} key.",
        writable=False,
    )

    # --- cross-tree-dep: pagamentos-recorrentes.md (MANUAL) -------------------
    rec_path = common.recurring_payments_path()
    rec_hit = False
    if rec_path.exists():
        try:
            rec_hit = from_cat in rec_path.read_text(encoding="utf-8")
        except Exception:
            rec_hit = False
    report.add(
        "cross-tree-dep",
        str(rec_path),
        (
            f"vault-content schedule's Categoria column MENTIONS {from_cat!r} "
            f"(p2-7 §1.18 / DC-1-G). NOT machine-rewritten — reconcile by hand."
            if rec_hit
            else f"recurring-payment schedule does not use {from_cat!r} (checked; "
            f"no manual edit needed)."
        ),
        writable=False,
    )

    report.warnings.append(
        "category-migrations.csv has NO active runtime consumer in categorize.py "
        "(it was dormant at p2-2/B2-IMP — see CONVENTION.md provenance). The LIVE "
        "re-categorization happens via the categories.json + suppliers.json edits "
        "above, which categorize.py DOES read. The correction row is the "
        "audit/provenance record."
    )
    report.warnings.append(
        f"Merging {from_cat!r} REMOVES it as a valid category. Any future "
        f"transaction the classifier would have placed in {from_cat!r} now lands "
        f"in {to_cat!r}. This is the intended retro-rewrite; confirm before --apply."
    )

    return report


def _surface_prior_migrations(from_cat: str) -> None:
    try:
        import query_corrections as qc  # type: ignore

        path = common.corrections_dir() / "category-migrations.csv"
        rows = qc.query_corrections_file(path, pattern=from_cat)
        if rows:
            print(f"\n[prior category-migrations touching {from_cat!r} — via query_corrections]")
            qc._print_table(rows)
    except Exception:
        pass


def _make_writers(
    report: common.ImpactReport,
    from_cat: str,
    to_cat: str,
    *,
    source: str,
    note: str,
) -> None:
    cfg = common.config_dir()
    categories_path = cfg / "categories.json"
    suppliers_path = cfg / "suppliers.json"
    cat_mig_path = common.corrections_dir() / "category-migrations.csv"

    for imp in report.impacts:
        if not imp.writable:
            continue
        loc = Path(imp.location)

        if loc == cat_mig_path:
            def _w_mig() -> None:
                common.append_correction_row(
                    cat_mig_path,
                    _CAT_MIGRATIONS_FIELDS,
                    {
                        "from_category": from_cat,
                        "to_category": to_cat,
                        "scope": "all",
                        "effective_after": "",
                        "added_at": common.now_iso(),
                        "source": source,
                        "note": note,
                    },
                )

            imp.writer = _w_mig

        elif loc == categories_path:
            def _w_categories() -> None:
                doc = common.load_json(categories_path)
                cats = doc.get("categories", {})
                cats.pop(from_cat, None)
                for m in doc.get("value_based_mappings") or []:
                    if isinstance(m, dict) and m.get("category") == from_cat:
                        m["category"] = to_cat
                reimb = doc.get("reimbursement_mappings") or {}
                for k, v in list(reimb.items()):
                    if isinstance(v, dict) and v.get("category") == from_cat:
                        v["category"] = to_cat
                    elif isinstance(v, str) and v == from_cat:
                        reimb[k] = to_cat
                rr = doc.get("recurrence_rules") or {}
                dbc = rr.get("default_by_category") or {}
                if from_cat in dbc:
                    # Move the FROM default under TO only if TO has none yet.
                    val = dbc.pop(from_cat)
                    dbc.setdefault(to_cat, val)
                common.dump_json(categories_path, doc)

            imp.writer = _w_categories

        elif loc == suppliers_path:
            def _w_suppliers() -> None:
                doc = common.load_json(suppliers_path)
                suppliers = doc.get("suppliers", doc)
                for _slug, rec in suppliers.items():
                    if isinstance(rec, dict) and rec.get("default_category") == from_cat:
                        rec["default_category"] = to_cat
                common.dump_json(suppliers_path, doc)

            imp.writer = _w_suppliers


def run(args: argparse.Namespace) -> int:
    if args.rollback:
        manifest_path = (
            common.corrections_dir() / ".rollback" / f"{_TOOL}-{args.rollback}.json"
        )
        if not manifest_path.exists():
            print(f"ERROR: rollback manifest not found: {manifest_path}", file=sys.stderr)
            return 1
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        actions = common.rollback(manifest)
        print(f"Rolled back {_TOOL} run {args.rollback}:")
        for a in actions:
            print(f"  - {a}")
        return 0

    report = build_impact(args.from_cat, args.to_cat, source=args.source, note=args.note)

    applying = args.apply
    common.print_impact_report(report, applying=applying)
    _surface_prior_migrations(args.from_cat)

    if report.errors:
        print("\nRefusing to proceed — resolve the blocking errors above.", file=sys.stderr)
        return 1

    if not applying:
        return 0

    _make_writers(report, args.from_cat, args.to_cat, source=args.source, note=args.note)
    manifest = common.apply_writes(report, source_function="merge_categories.run")
    mpath = common.write_manifest(manifest, label=_TOOL)
    print(f"\nAPPLIED. Rollback token: {manifest['token']}")
    print(f"  Undo with: python merge_categories.py --rollback {manifest['token']}")
    print(f"  Manifest:  {mpath}")
    print(
        "\nNext: re-run `categorize.py --force` for affected months to regenerate "
        "transactions.csv with the merged category. Reconcile any cross-tree "
        "mention flagged above by hand."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Retro-rewrite: merge one category into another (dry-run by default)."
    )
    parser.add_argument("--from", dest="from_cat", help="Category to merge away (removed).")
    parser.add_argument("--to", dest="to_cat", help="Category to keep (merge target).")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute the write. WITHOUT this flag the tool is dry-run only.",
    )
    parser.add_argument("--source", default="merge_categories", help="Provenance source field.")
    parser.add_argument("--note", default="", help="Human note recorded in the correction row.")
    parser.add_argument(
        "--rollback", metavar="TOKEN", help="Undo a prior --apply run by its rollback token."
    )
    args = parser.parse_args(argv)

    if not args.rollback and (not args.from_cat or not args.to_cat):
        parser.error("--from and --to are required unless --rollback is given.")
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
