"""rename_canonical: retro-rewrite tool — rename a vendor's canonical name (p4-26).

WRITE-class, use=retro-rewrite. Renames a supplier's canonical display name
(`--from "Old Name" --to "New Name"`) by:
  1. Appending a row to the append-only `corrections/vendor-canonicals.csv`
     side-ledger (raw_vendor -> canonical_vendor; the durable record; rows are
     never edited in place).
  2. Updating `config/suppliers.json`: rewrite the matched supplier's `canonical`
     field to the new name (the classifier's live source for the
     `supplier_canonical` output column).

It NEVER edits historical ledger rows. The `supplier_canonical` column in
`transactions.csv` is regenerated by `categorize.py` from suppliers.json at read
time — this tool enumerates the affected rows but does not rewrite them.

Affected locations enumerated by the fix-impact preview, BEFORE any write:
  * correction-ledger: vendor-canonicals.csv (the append target)
  * config: suppliers.json (the matched supplier's `canonical` field)
  * output-rows: transactions.csv rows whose `supplier_canonical` == OLD name
  * cross-tree-dep: 2-areas/finance/pagamentos-recorrentes.md (a vault-content
    schedule that may list the vendor by its display name — MANUAL reconcile)

DRY-RUN IS THE DEFAULT. A real write requires --apply, is backed up before
writing, and is reversible via --rollback TOKEN.

Composes the existing read tool `audit-aliases.py` to flag whether the rename
would create an alias ambiguity (the SAME alias resolving to two suppliers).

Usage:
    python rename_canonical.py --from "Old" --to "New"            # DRY-RUN
    python rename_canonical.py --from "Old" --to "New" --apply     # execute
    python rename_canonical.py --slug some-slug --to "New" --apply # match by slug
    python rename_canonical.py --rollback TOKEN                     # undo

Exit codes:
    0  preview rendered / apply succeeded / rollback succeeded
    1  blocking error (no matching supplier, ambiguous match, etc.)
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import _retro_rewrite_common as common  # noqa: E402

_TOOL = "rename_canonical"
_VENDOR_CANON_FIELDS = ["raw_vendor", "canonical_vendor", "scope", "added_at", "source", "note"]


def _find_suppliers_by_canonical(suppliers: dict, name: str) -> list[str]:
    return [
        slug
        for slug, rec in suppliers.items()
        if isinstance(rec, dict) and (rec.get("canonical") or "") == name
    ]


def build_impact(
    *,
    from_name: str | None,
    to_name: str,
    slug: str | None,
    source: str,
    note: str,
) -> common.ImpactReport:
    op_from = slug if slug else from_name
    report = common.ImpactReport(
        tool=_TOOL, operation=f"rename canonical {op_from!r} -> {to_name!r}"
    )
    cfg = common.config_dir()
    suppliers_path = cfg / "suppliers.json"
    vendor_canon_path = common.corrections_dir() / "vendor-canonicals.csv"

    if not suppliers_path.exists():
        report.errors.append(f"suppliers.json not found at {suppliers_path}")
        return report

    sup_doc = common.load_json(suppliers_path)
    suppliers = sup_doc.get("suppliers", sup_doc)

    # --- Resolve the target supplier ------------------------------------------
    target_slugs: list[str]
    resolved_old_name = from_name
    if slug:
        if slug not in suppliers:
            report.errors.append(f"supplier slug {slug!r} not found in suppliers.json")
            return report
        target_slugs = [slug]
        resolved_old_name = (suppliers[slug].get("canonical") or "") if isinstance(
            suppliers[slug], dict
        ) else ""
    else:
        target_slugs = _find_suppliers_by_canonical(suppliers, from_name or "")
        if not target_slugs:
            report.errors.append(
                f"no supplier has canonical == {from_name!r}. Use --slug to target "
                f"by slug, or check the exact canonical spelling."
            )
            return report
        if len(target_slugs) > 1:
            report.errors.append(
                f"{len(target_slugs)} suppliers share canonical {from_name!r} "
                f"({', '.join(target_slugs)}). Disambiguate with --slug."
            )
            return report

    matched_slug = target_slugs[0]

    # --- correction-ledger: vendor-canonicals.csv (write target) --------------
    report.add(
        "correction-ledger",
        str(vendor_canon_path),
        f"append row: raw_vendor={resolved_old_name}, canonical_vendor={to_name}, scope=all",
        writable=True,
        materiality="high",
    )

    # --- config: suppliers.json canonical field (write target) ----------------
    report.add(
        "config",
        str(suppliers_path),
        f"supplier {matched_slug!r}: canonical {resolved_old_name!r} -> {to_name!r}",
        writable=True,
        materiality="high",
    )

    # --- output-rows: transactions.csv supplier_canonical (affected) ----------
    row_hits = 0
    months: set[str] = set()
    for month, _txfile, row in common.iter_transactions_rows():
        if (row.get("supplier_canonical", "") or "") == (resolved_old_name or ""):
            row_hits += 1
            months.add(month)
    if row_hits:
        report.add(
            "output-rows",
            str(common.ledger_fechamento_dir()),
            f"{row_hits} transactions.csv row(s) across {len(months)} month(s) "
            f"({', '.join(sorted(months))}) carry supplier_canonical=={resolved_old_name!r}. "
            f"These regenerate via categorize.py on the next close — NOT rewritten here.",
            writable=False,
        )

    # --- cross-tree-dep: pagamentos-recorrentes.md (MANUAL) -------------------
    rec_path = common.recurring_payments_path()
    rec_hit = False
    if rec_path.exists() and resolved_old_name:
        try:
            text = rec_path.read_text(encoding="utf-8")
            rec_hit = resolved_old_name in text
        except Exception:
            rec_hit = False
    report.add(
        "cross-tree-dep",
        str(rec_path),
        (
            f"vault-content recurring-payment schedule MENTIONS {resolved_old_name!r} "
            f"(p2-7 §1.18 / DC-1-G). This file is NOT machine-rewritten — reconcile "
            f"the display name by hand."
            if rec_hit
            else f"recurring-payment schedule does not mention {resolved_old_name!r} "
            f"(checked; no manual edit needed)."
        ),
        writable=False,
    )

    # --- alias-collision advisory via audit-aliases composition ---------------
    report.warnings.append(
        "vendor-canonicals.csv has NO active runtime consumer in categorize.py "
        "yet; the LIVE rename takes effect through the suppliers.json `canonical` "
        "edit above (which categorize.py reads). The correction row is the "
        "audit/provenance record."
    )

    return report


def _surface_alias_audit() -> None:
    """Compose audit-aliases.py (read tool) to show current alias ambiguities."""
    try:
        scripts_dir = _HERE.parent / "shared"
        mod_path = scripts_dir / "audit-aliases.py"
        if not mod_path.exists():
            return
        spec = importlib.util.spec_from_file_location("audit_aliases", mod_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore
        suppliers_path = common.config_dir() / "suppliers.json"
        alias_map = mod.load_alias_map(suppliers_path)
        dups = mod.find_duplicates(alias_map)
        if dups:
            print("\n[alias ambiguities currently present — via audit-aliases]")
            for alias, slugs in list(dups.items())[:10]:
                print(f"  {alias!r}: {', '.join(slugs)}")
    except Exception:
        pass


def _make_writers(
    report: common.ImpactReport,
    *,
    matched_old_name: str,
    to_name: str,
    source: str,
    note: str,
) -> None:
    cfg = common.config_dir()
    suppliers_path = cfg / "suppliers.json"
    vendor_canon_path = common.corrections_dir() / "vendor-canonicals.csv"

    for imp in report.impacts:
        if not imp.writable:
            continue
        loc = Path(imp.location)

        if loc == vendor_canon_path:
            def _w_canon() -> None:
                common.append_correction_row(
                    vendor_canon_path,
                    _VENDOR_CANON_FIELDS,
                    {
                        "raw_vendor": matched_old_name,
                        "canonical_vendor": to_name,
                        "scope": "all",
                        "added_at": common.now_iso(),
                        "source": source,
                        "note": note,
                    },
                )

            imp.writer = _w_canon

        elif loc == suppliers_path:
            def _w_suppliers() -> None:
                doc = common.load_json(suppliers_path)
                suppliers = doc.get("suppliers", doc)
                for _slug, rec in suppliers.items():
                    if isinstance(rec, dict) and (rec.get("canonical") or "") == matched_old_name:
                        rec["canonical"] = to_name
                common.dump_json(suppliers_path, doc)

            imp.writer = _w_suppliers


def run(args: argparse.Namespace) -> int:
    if args.rollback:
        manifest_path = (
            common.corrections_dir() / ".rollback" / f"{_TOOL}-{args.rollback}.json"
        )
        if not manifest_path.exists():
            print(f"ERROR: rollback manifest not found: {manifest_path}", file=sys.stderr)
            return 1
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        actions = common.rollback(manifest)
        print(f"Rolled back {_TOOL} run {args.rollback}:")
        for a in actions:
            print(f"  - {a}")
        return 0

    report = build_impact(
        from_name=args.from_name,
        to_name=args.to_name,
        slug=args.slug,
        source=args.source,
        note=args.note,
    )

    applying = args.apply
    common.print_impact_report(report, applying=applying)
    _surface_alias_audit()

    if report.errors:
        print("\nRefusing to proceed — resolve the blocking errors above.", file=sys.stderr)
        return 1

    if not applying:
        return 0

    # Resolve the matched old canonical name for the writers (config edit keys on it).
    cfg = common.config_dir()
    sup_doc = common.load_json(cfg / "suppliers.json")
    suppliers = sup_doc.get("suppliers", sup_doc)
    if args.slug:
        matched_old = (suppliers[args.slug].get("canonical") or "")
    else:
        matched_old = args.from_name

    _make_writers(
        report,
        matched_old_name=matched_old,
        to_name=args.to_name,
        source=args.source,
        note=args.note,
    )
    manifest = common.apply_writes(report, source_function="rename_canonical.run")
    mpath = common.write_manifest(manifest, label=_TOOL)
    print(f"\nAPPLIED. Rollback token: {manifest['token']}")
    print(f"  Undo with: python rename_canonical.py --rollback {manifest['token']}")
    print(f"  Manifest:  {mpath}")
    print(
        "\nNext: re-run `categorize.py --force` for affected months to regenerate "
        "transactions.csv with the renamed canonical. Reconcile any cross-tree "
        "mention flagged above by hand."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Retro-rewrite: rename a vendor canonical name (dry-run by default)."
    )
    parser.add_argument("--from", dest="from_name", help="Current canonical name to rename.")
    parser.add_argument("--to", dest="to_name", help="New canonical name.")
    parser.add_argument("--slug", help="Target supplier by slug (disambiguates duplicate canonicals).")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute the write. WITHOUT this flag the tool is dry-run only.",
    )
    parser.add_argument("--source", default="rename_canonical", help="Provenance source field.")
    parser.add_argument("--note", default="", help="Human note recorded in the correction row.")
    parser.add_argument(
        "--rollback", metavar="TOKEN", help="Undo a prior --apply run by its rollback token."
    )
    args = parser.parse_args(argv)

    if not args.rollback:
        if not args.to_name:
            parser.error("--to is required unless --rollback is given.")
        if not args.from_name and not args.slug:
            parser.error("one of --from or --slug is required unless --rollback is given.")
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
