"""rename_tags: retro-rewrite tool — rename a tag across the tag namespace (p4-26).

WRITE-class, use=retro-rewrite. Renames a tag (`--from OLD --to NEW`) by:
  1. Appending a row to the append-only `corrections/tag-renames.csv` side-ledger
     (the durable record of the rename; rows are never edited in place).
  2. Updating `config/tags.json`: rename the tag key OLD -> NEW (preserving its
     label/added), and record OLD in the `rejected` list so the old name is not
     silently re-added.

It NEVER edits historical ledger rows. `transactions.csv` tag values are
regenerated by `categorize.py` (which re-stamps tags from suppliers.json
default_tags + reimbursement_mappings at read time) — this tool enumerates the
affected rows in the fix-impact preview but does not rewrite them.

Affected locations enumerated by the fix-impact preview, BEFORE any write:
  * config: tags.json (the tag key), suppliers.json default_tags arrays,
    categories.json reimbursement_mappings.*.tag
  * correction-ledger: tag-renames.csv (the append target)
  * output-rows: transactions.csv rows carrying OLD in their `tags` column
  * tag-namespace: the OLD/NEW collision check (NEW must not pre-exist unless
    --merge-into-existing is given)

DRY-RUN IS THE DEFAULT. A real write requires --apply. A real run is reversible:
every written file is backed up to a timestamped .bak first, and a rollback
manifest is persisted under corrections/.rollback/.

Composes the existing read tool `query_corrections.py` to surface any prior
tag-rename correction for the same tag before writing a new one.

Usage:
    python rename_tags.py --from OLD --to NEW            # DRY-RUN preview
    python rename_tags.py --from OLD --to NEW --apply    # execute (reversible)
    python rename_tags.py --from OLD --to NEW --apply --merge-into-existing
    python rename_tags.py --rollback TOKEN               # undo a prior --apply

Exit codes:
    0  preview rendered / apply succeeded / rollback succeeded
    1  blocking error (tag missing, NEW collision without --merge, etc.)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import _retro_rewrite_common as common  # noqa: E402

_TOOL = "rename_tags"
_TAG_RENAMES_FIELDS = ["from_tag", "to_tag", "scope", "added_at", "source", "note"]


# ---------------------------------------------------------------------------
# Impact analysis (read-only)
# ---------------------------------------------------------------------------


def build_impact(
    from_tag: str,
    to_tag: str,
    *,
    merge_into_existing: bool,
    source: str,
    note: str,
) -> common.ImpactReport:
    report = common.ImpactReport(
        tool=_TOOL, operation=f"rename tag {from_tag!r} -> {to_tag!r}"
    )
    cfg = common.config_dir()
    tags_path = cfg / "tags.json"
    suppliers_path = cfg / "suppliers.json"
    categories_path = cfg / "categories.json"
    renames_path = common.corrections_dir() / "tag-renames.csv"

    # --- Validate the tag namespace (tags.json) -------------------------------
    tags_doc = common.load_json(tags_path) if tags_path.exists() else {}
    tags_map = tags_doc.get("tags", {})
    rejected = tags_doc.get("rejected", [])

    if from_tag not in tags_map:
        report.errors.append(
            f"tag {from_tag!r} not found in tags.json — nothing to rename. "
            f"(present tags: {', '.join(sorted(tags_map)) or 'none'})"
        )
    to_exists = to_tag in tags_map
    if to_exists and not merge_into_existing:
        report.errors.append(
            f"target tag {to_tag!r} already exists in tags.json — refusing to "
            f"clobber. Pass --merge-into-existing to fold {from_tag!r} into it "
            f"(the existing {to_tag!r} label is kept)."
        )

    # --- correction-ledger: tag-renames.csv (the write target) ----------------
    report.add(
        "correction-ledger",
        str(renames_path),
        f"append row: from_tag={from_tag}, to_tag={to_tag}, scope=all",
        writable=True,
        materiality="high",
    )

    # --- config: tags.json (rename key, record old in rejected) ----------------
    if from_tag in tags_map:
        action = (
            f"fold {from_tag!r} into existing {to_tag!r}; record {from_tag!r} in rejected"
            if to_exists
            else f"rename key {from_tag!r} -> {to_tag!r}; record {from_tag!r} in rejected"
        )
        report.add(
            "config",
            str(tags_path),
            action,
            writable=True,
            materiality="high",
        )

    # --- config: suppliers.json default_tags arrays (affected, regenerated) ----
    sup_hits = []
    if suppliers_path.exists():
        sup_doc = common.load_json(suppliers_path)
        suppliers = sup_doc.get("suppliers", sup_doc)
        for slug, rec in suppliers.items():
            if isinstance(rec, dict) and from_tag in (rec.get("default_tags") or []):
                sup_hits.append(slug)
    if sup_hits:
        report.add(
            "config",
            str(suppliers_path),
            f"{len(sup_hits)} supplier(s) carry {from_tag!r} in default_tags "
            f"({', '.join(sup_hits[:8])}{'…' if len(sup_hits) > 8 else ''}) — "
            f"rewrite default_tags {from_tag!r} -> {to_tag!r}",
            writable=True,
            materiality="medium",
        )

    # --- config: categories.json reimbursement_mappings.*.tag ------------------
    reimb_hits = []
    if categories_path.exists():
        cat_doc = common.load_json(categories_path)
        for key, val in (cat_doc.get("reimbursement_mappings") or {}).items():
            if isinstance(val, dict) and val.get("tag") == from_tag:
                reimb_hits.append(key)
    if reimb_hits:
        report.add(
            "config",
            str(categories_path),
            f"{len(reimb_hits)} reimbursement_mapping(s) set tag={from_tag!r} "
            f"({', '.join(reimb_hits)}) — rewrite tag -> {to_tag!r}",
            writable=True,
            materiality="medium",
        )

    # --- output-rows: transactions.csv tag values (affected, NOT written) ------
    row_hits = 0
    months: set[str] = set()
    for month, _txfile, row in common.iter_transactions_rows():
        tags_field = row.get("tags", "") or ""
        parts = [t.strip() for t in tags_field.replace(",", ";").split(";") if t.strip()]
        if from_tag in parts:
            row_hits += 1
            months.add(month)
    if row_hits:
        report.add(
            "output-rows",
            str(common.ledger_fechamento_dir()),
            f"{row_hits} transactions.csv row(s) across {len(months)} month(s) "
            f"({', '.join(sorted(months))}) carry {from_tag!r} in `tags`. These "
            f"regenerate via categorize.py on the next close — NOT rewritten here.",
            writable=False,
        )

    # --- tag-namespace: collision / rejected bookkeeping -----------------------
    report.add(
        "tag-namespace",
        "tags.json::rejected",
        f"record {from_tag!r} in rejected so it is not silently re-added "
        f"(per DC-3 namespace hygiene, p2-7 §2.3)",
        writable=False,
    )

    # --- consumer-wiring advisory (silent-wrong guard) -------------------------
    report.warnings.append(
        "tag-renames.csv has NO active runtime consumer in categorize.py yet "
        "(the durable record is written, but the LIVE re-tagging happens via the "
        "tags.json + suppliers.json + reimbursement_mappings edits above, which "
        "categorize.py DOES read). The correction row is the audit/provenance "
        "record; the config edits are what actually change classification."
    )

    return report


def _surface_prior_renames(from_tag: str) -> None:
    """Compose query_corrections.py to show any prior rename for this tag."""
    try:
        import query_corrections as qc  # type: ignore

        path = common.corrections_dir() / "tag-renames.csv"
        rows = qc.query_corrections_file(path, pattern=from_tag)
        if rows:
            print(f"\n[prior tag-renames touching {from_tag!r} — via query_corrections]")
            qc._print_table(rows)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Writers (only invoked under --apply, after backup)
# ---------------------------------------------------------------------------


def _make_writers(
    report: common.ImpactReport,
    from_tag: str,
    to_tag: str,
    *,
    merge_into_existing: bool,
    source: str,
    note: str,
) -> None:
    cfg = common.config_dir()
    tags_path = cfg / "tags.json"
    suppliers_path = cfg / "suppliers.json"
    categories_path = cfg / "categories.json"
    renames_path = common.corrections_dir() / "tag-renames.csv"

    for imp in report.impacts:
        if not imp.writable:
            continue
        loc = Path(imp.location)

        if loc == renames_path:
            def _w_renames() -> None:
                common.append_correction_row(
                    renames_path,
                    _TAG_RENAMES_FIELDS,
                    {
                        "from_tag": from_tag,
                        "to_tag": to_tag,
                        "scope": "all",
                        "added_at": common.now_iso(),
                        "source": source,
                        "note": note,
                    },
                )

            imp.writer = _w_renames

        elif loc == tags_path:
            def _w_tags() -> None:
                doc = common.load_json(tags_path)
                tags_map = doc.setdefault("tags", {})
                rejected = doc.setdefault("rejected", [])
                old_def = tags_map.pop(from_tag, None)
                if not merge_into_existing and old_def is not None:
                    # Rename: carry the old definition under the new key unless
                    # the new key already exists.
                    tags_map.setdefault(to_tag, old_def)
                # else merge: keep the existing to_tag definition as-is.
                if not any(
                    isinstance(r, dict) and r.get("token") == from_tag for r in rejected
                ):
                    rejected.append(
                        {
                            "token": from_tag,
                            "date": common.now_iso()[:10],
                            "reason": f"renamed to {to_tag!r} via {_TOOL}",
                            "return_count": 0,
                        }
                    )
                common.dump_json(tags_path, doc)

            imp.writer = _w_tags

        elif loc == suppliers_path:
            def _w_suppliers() -> None:
                doc = common.load_json(suppliers_path)
                suppliers = doc.get("suppliers", doc)
                for _slug, rec in suppliers.items():
                    if not isinstance(rec, dict):
                        continue
                    dt = rec.get("default_tags")
                    if dt and from_tag in dt:
                        rec["default_tags"] = [
                            (to_tag if t == from_tag else t) for t in dt
                        ]
                        # De-dup if both old and new were present.
                        seen: list = []
                        for t in rec["default_tags"]:
                            if t not in seen:
                                seen.append(t)
                        rec["default_tags"] = seen
                common.dump_json(suppliers_path, doc)

            imp.writer = _w_suppliers

        elif loc == categories_path:
            def _w_categories() -> None:
                doc = common.load_json(categories_path)
                for _key, val in (doc.get("reimbursement_mappings") or {}).items():
                    if isinstance(val, dict) and val.get("tag") == from_tag:
                        val["tag"] = to_tag
                common.dump_json(categories_path, doc)

            imp.writer = _w_categories


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def run(args: argparse.Namespace) -> int:
    if args.rollback:
        manifest_path = (
            common.corrections_dir() / ".rollback" / f"{_TOOL}-{args.rollback}.json"
        )
        if not manifest_path.exists():
            print(f"ERROR: rollback manifest not found: {manifest_path}", file=sys.stderr)
            return 1
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        actions = common.rollback(manifest)
        print(f"Rolled back {_TOOL} run {args.rollback}:")
        for a in actions:
            print(f"  - {a}")
        return 0

    report = build_impact(
        args.from_tag,
        args.to_tag,
        merge_into_existing=args.merge_into_existing,
        source=args.source,
        note=args.note,
    )

    applying = args.apply
    common.print_impact_report(report, applying=applying)
    _surface_prior_renames(args.from_tag)

    if report.errors:
        print("\nRefusing to proceed — resolve the blocking errors above.", file=sys.stderr)
        return 1

    if not applying:
        return 0

    _make_writers(
        report,
        args.from_tag,
        args.to_tag,
        merge_into_existing=args.merge_into_existing,
        source=args.source,
        note=args.note,
    )
    manifest = common.apply_writes(report, source_function="rename_tags.run")
    mpath = common.write_manifest(manifest, label=_TOOL)
    print(f"\nAPPLIED. Rollback token: {manifest['token']}")
    print(f"  Undo with: python rename_tags.py --rollback {manifest['token']}")
    print(f"  Manifest:  {mpath}")
    print(
        "\nNext: re-run `categorize.py --force` for affected months to regenerate "
        "transactions.csv with the renamed tag."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Retro-rewrite: rename a tag across the tag namespace (dry-run by default)."
    )
    parser.add_argument("--from", dest="from_tag", help="Tag to rename (current name).")
    parser.add_argument("--to", dest="to_tag", help="New tag name.")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute the write. WITHOUT this flag the tool is dry-run only.",
    )
    parser.add_argument(
        "--merge-into-existing",
        action="store_true",
        help="Allow folding into an already-existing target tag (keeps its label).",
    )
    parser.add_argument("--source", default="rename_tags", help="Provenance source field.")
    parser.add_argument("--note", default="", help="Human note recorded in the correction row.")
    parser.add_argument(
        "--rollback",
        metavar="TOKEN",
        help="Undo a prior --apply run by its rollback token.",
    )
    args = parser.parse_args(argv)

    if not args.rollback and (not args.from_tag or not args.to_tag):
        parser.error("--from and --to are required unless --rollback is given.")
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
